# Generated by Django 5.2.4 on 2025-12-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_deliveryaddress_address_cart_orders_order_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/default.jpg', null=True, upload_to='profile_pic/%Y/%m/%d/'),
        ),
    ]
