# Generated by Django 5.2.4 on 2025-12-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_custom_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
