# Generated by Django 5.2.4 on 2025-12-08 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_order_items_return_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='transactions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='Users.wallet'),
        ),
    ]
