# Generated by Django 5.2.4 on 2025-12-08 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_wallet_transactions_alter_transactions_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='Users.wallet'),
        ),
    ]
