# Generated by Django 5.2.4 on 2025-12-08 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_transactions_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='transactions',
            new_name='transaction',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.wallet'),
        ),
    ]
