# Generated by Django 5.2.4 on 2025-12-08 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_rename_transactions_wallet_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transaction', to='Users.wallet'),
        ),
    ]
