# Generated by Django 5.2.4 on 2025-12-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_transactions_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='transaction',
        ),
        migrations.AddField(
            model_name='transactions',
            name='narration',
            field=models.CharField(default='Initial transaction', max_length=255),
        ),
    ]
