# Generated by Django 5.2.4 on 2025-12-08 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_remove_wallet_transaction_transactions_narration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='narration',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.wallet'),
        ),
    ]
